
class PreProcess_LoginTag() :

    @classmethod
    def MakePreProcess_LoginTag_P0_1_1(self, makeInfo):
        orderSQL1 = """
            INSERT OVERWRITE TABLE gtwpd.model_usedata PARTITION ( product = '[:ProductName]' , project = '[:Project]' ,version = '[:PreProcessVersion]' , dt = '[:DateNoLine]' , step = 'PreProcess')
            SELECT 
                AA.commondata_1 as commondata_1
                , null as commondata_2
                , null as commondata_3
                , null as commondata_4
                , AA.commondata_5 as commondata_5
                , AA.commondata_6 as commondata_6
                , NULL AS commondata_7
                , NULL AS commondata_8
                , NULL AS commondata_9
                , NULL AS commondata_10
                , NULL AS commondata_11
                , NULL AS commondata_12
                , NULL AS commondata_13
                , NULL AS commondata_14
                , NULL AS commondata_15
                , AA.UniqueFloat_001 as UniqueFloat_001
                , AA.UniqueFloat_002 AS UniqueFloat_002 
                , AA.UniqueFloat_003 AS UniqueFloat_003 
                , AA.UniqueFloat_004 AS UniqueFloat_004
                , AA.UniqueFloat_005 AS UniqueFloat_005
                , AA.UniqueFloat_006 AS UniqueFloat_006 
                , NULL AS UniqueFloat_007
                , NULL AS UniqueFloat_008
                , NULL AS UniqueFloat_009
                , NULL AS UniqueFloat_010
                , NULL AS UniqueFloat_011
                , NULL AS UniqueFloat_012
                , NULL AS UniqueFloat_013
                , NULL AS UniqueFloat_014
                , NULL AS UniqueFloat_015
                , NULL AS UniqueFloat_016
                , NULL AS UniqueFloat_017
                , NULL AS UniqueFloat_018
                , NULL AS UniqueFloat_019
                , NULL AS UniqueFloat_020
                , NULL AS UniqueFloat_021
                , NULL AS UniqueFloat_022
                , NULL AS UniqueFloat_023
                , NULL AS UniqueFloat_024
                , NULL AS UniqueFloat_025
                , NULL AS UniqueFloat_026
                , NULL AS UniqueFloat_027
                , NULL AS UniqueFloat_028
                , NULL AS UniqueFloat_029
                , NULL AS UniqueFloat_030
                , NULL AS UniqueFloat_031
                , NULL AS UniqueFloat_032
                , NULL AS UniqueFloat_033
                , NULL AS UniqueFloat_034
                , NULL AS UniqueFloat_035
                , NULL AS UniqueFloat_036
                , NULL AS UniqueFloat_037
                , NULL AS UniqueFloat_038
                , NULL AS UniqueFloat_039
                , NULL AS UniqueFloat_040
                , NULL AS UniqueFloat_041
                , NULL AS UniqueFloat_042
                , NULL AS UniqueFloat_043
                , NULL AS UniqueFloat_044
                , NULL AS UniqueFloat_045
                , NULL AS UniqueFloat_046
                , NULL AS UniqueFloat_047
                , NULL AS UniqueFloat_048
                , NULL AS UniqueFloat_049
                , NULL AS UniqueFloat_050
                , NULL AS UniqueFloat_051
                , NULL AS UniqueFloat_052
                , NULL AS UniqueFloat_053
                , NULL AS UniqueFloat_054
                , NULL AS UniqueFloat_055
                , NULL AS UniqueFloat_056
                , NULL AS UniqueFloat_057
                , NULL AS UniqueFloat_058
                , NULL AS UniqueFloat_059
                , NULL AS UniqueFloat_060
                , NULL AS UniqueFloat_061
                , NULL AS UniqueFloat_062
                , NULL AS UniqueFloat_063
                , NULL AS UniqueFloat_064
                , NULL AS UniqueFloat_065
                , NULL AS UniqueFloat_066
                , NULL AS UniqueFloat_067
                , NULL AS UniqueFloat_068
                , NULL AS UniqueFloat_069
                , NULL AS UniqueFloat_070
                , NULL AS UniqueFloat_071
                , NULL AS UniqueFloat_072
                , NULL AS UniqueFloat_073
                , NULL AS UniqueFloat_074
                , NULL AS UniqueFloat_075
                , NULL AS UniqueFloat_076
                , NULL AS UniqueFloat_077
                , NULL AS UniqueFloat_078
                , NULL AS UniqueFloat_079
                , NULL AS UniqueFloat_080
                , NULL AS UniqueFloat_081
                , NULL AS UniqueFloat_082
                , NULL AS UniqueFloat_083
                , NULL AS UniqueFloat_084
                , NULL AS UniqueFloat_085
                , NULL AS UniqueFloat_086
                , NULL AS UniqueFloat_087
                , NULL AS UniqueFloat_088
                , NULL AS UniqueFloat_089
                , NULL AS UniqueFloat_090
                , NULL AS UniqueFloat_091
                , NULL AS UniqueFloat_092
                , NULL AS UniqueFloat_093
                , NULL AS UniqueFloat_094
                , NULL AS UniqueFloat_095
                , NULL AS UniqueFloat_096
                , NULL AS UniqueFloat_097
                , NULL AS UniqueFloat_098
                , NULL AS UniqueFloat_099
                , NULL AS UniqueFloat_100
                , NULL AS UniqueFloat_101
                , NULL AS UniqueFloat_102
                , NULL AS UniqueFloat_103
                , NULL AS UniqueFloat_104
                , NULL AS UniqueFloat_105
                , NULL AS UniqueFloat_106
                , NULL AS UniqueFloat_107
                , NULL AS UniqueFloat_108
                , NULL AS UniqueFloat_109
                , NULL AS UniqueFloat_110
                , NULL AS UniqueFloat_111
                , NULL AS UniqueFloat_112
                , NULL AS UniqueFloat_113
                , NULL AS UniqueFloat_114
                , NULL AS UniqueFloat_115
                , NULL AS UniqueFloat_116
                , NULL AS UniqueFloat_117
                , NULL AS UniqueFloat_118
                , NULL AS UniqueFloat_119
                , NULL AS UniqueFloat_120
                , NULL AS UniqueFloat_121
                , NULL AS UniqueFloat_122
                , NULL AS UniqueFloat_123
                , NULL AS UniqueFloat_124
                , NULL AS UniqueFloat_125
                , NULL AS UniqueFloat_126
                , NULL AS UniqueFloat_127
                , NULL AS UniqueFloat_128
                , NULL AS UniqueFloat_129
                , NULL AS UniqueFloat_130
                , NULL AS UniqueFloat_131
                , NULL AS UniqueFloat_132
                , NULL AS UniqueFloat_133
                , NULL AS UniqueFloat_134
                , NULL AS UniqueFloat_135
                , NULL AS UniqueFloat_136
                , NULL AS UniqueFloat_137
                , NULL AS UniqueFloat_138
                , NULL AS UniqueFloat_139
                , NULL AS UniqueFloat_140
                , NULL AS UniqueFloat_141
                , NULL AS UniqueFloat_142
                , NULL AS UniqueFloat_143
                , NULL AS UniqueFloat_144
                , NULL AS UniqueFloat_145
                , NULL AS UniqueFloat_146
                , NULL AS UniqueFloat_147
                , NULL AS UniqueFloat_148
                , NULL AS UniqueFloat_149
                , NULL AS UniqueFloat_150
                , NULL AS UniqueFloat_151
                , NULL AS UniqueFloat_152
                , NULL AS UniqueFloat_153
                , NULL AS UniqueFloat_154
                , NULL AS UniqueFloat_155
                , NULL AS UniqueFloat_156
                , NULL AS UniqueFloat_157
                , NULL AS UniqueFloat_158
                , NULL AS UniqueFloat_159
                , NULL AS UniqueFloat_160
                , NULL AS UniqueFloat_161
                , NULL AS UniqueFloat_162
                , NULL AS UniqueFloat_163
                , NULL AS UniqueFloat_164
                , NULL AS UniqueFloat_165
                , NULL AS UniqueFloat_166
                , NULL AS UniqueFloat_167
                , NULL AS UniqueFloat_168
                , NULL AS UniqueFloat_169
                , NULL AS UniqueFloat_170
                , NULL AS UniqueFloat_171
                , NULL AS UniqueFloat_172
                , NULL AS UniqueFloat_173
                , NULL AS UniqueFloat_174
                , NULL AS UniqueFloat_175
                , NULL AS UniqueFloat_176
                , NULL AS UniqueFloat_177
                , NULL AS UniqueFloat_178
                , NULL AS UniqueFloat_179
                , NULL AS UniqueFloat_180
                , NULL AS UniqueFloat_181
                , NULL AS UniqueFloat_182
                , NULL AS UniqueFloat_183
                , NULL AS UniqueFloat_184
                , NULL AS UniqueFloat_185
                , NULL AS UniqueFloat_186
                , NULL AS UniqueFloat_187
                , NULL AS UniqueFloat_188
                , NULL AS UniqueFloat_189
                , NULL AS UniqueFloat_190
                , NULL AS UniqueFloat_191
                , NULL AS UniqueFloat_192
                , NULL AS UniqueFloat_193
                , NULL AS UniqueFloat_194
                , NULL AS UniqueFloat_195
                , NULL AS UniqueFloat_196
                , NULL AS UniqueFloat_197
                , NULL AS UniqueFloat_198
                , NULL AS UniqueFloat_199
                , NULL AS UniqueFloat_200
                , NULL AS UniqueJson_001 
            FROM gtwpd.model_usedata AA 
            WHERE 1 = 1
                AND AA.product = 'maple' 
                AND AA.project = 'LoginTag' 
                AND AA.version = 'R0_1_2'
                AND AA.dt = '[:DateNoLine]'
                AND AA.step = 'RawData'; 
        """
        return "MakePreProcessOrderSQLInsert", [orderSQL1]

    @classmethod
    def MakePreProcess_LoginTag_P0_1_2(self, makeInfo):
        orderSQL1 = """
            INSERT OVERWRITE TABLE gtwpd.model_usedata PARTITION ( product = '[:ProductName]' , project = '[:Project]' ,version = '[:PreProcessVersion]' , dt = '[:DateNoLine]' , step = 'PreProcess')
            SELECT 
                AA.commondata_001 as commondata_001
                , null as commondata_002
                , null as commondata_003
                , null as commondata_004
                , AA.commondata_005 as commondata_005
                , AA.commondata_006 as commondata_006
                , NULL AS commondata_007
                , NULL AS commondata_008
                , NULL AS commondata_009
                , NULL AS commondata_010
                , NULL AS commondata_011
                , NULL AS commondata_012
                , NULL AS commondata_013
                , NULL AS commondata_014
                , NULL AS commondata_015
                , (AA.uniquefloat_001 + AA.uniquefloat_002 + AA.uniquefloat_003 + AA.uniquefloat_004 + AA.uniquefloat_005 + AA.uniquefloat_006 + AA.uniquefloat_007 + AA.uniquefloat_008
                + AA.uniquefloat_145 + AA.uniquefloat_146 + AA.uniquefloat_147 + AA.uniquefloat_148 + AA.uniquefloat_149 + AA.uniquefloat_150 + AA.uniquefloat_151 + AA.uniquefloat_152)/3600/2/8 as UniqueFloat_001     
                , (AA.uniquefloat_009 + AA.uniquefloat_010 + AA.uniquefloat_011 + AA.uniquefloat_012 + AA.uniquefloat_013 + AA.uniquefloat_014 + AA.uniquefloat_015 + AA.uniquefloat_016  
                + AA.uniquefloat_153 + AA.uniquefloat_154 + AA.uniquefloat_155 + AA.uniquefloat_156 + AA.uniquefloat_157 + AA.uniquefloat_158 + AA.uniquefloat_159 + AA.uniquefloat_160)/3600/2/8 as UniqueFloat_002   
                , (AA.uniquefloat_017 + AA.uniquefloat_018 + AA.uniquefloat_019 + AA.uniquefloat_020 + AA.uniquefloat_021 + AA.uniquefloat_022 + AA.uniquefloat_023 + AA.uniquefloat_024 
                + AA.uniquefloat_161 + AA.uniquefloat_162 + AA.uniquefloat_163 + AA.uniquefloat_164 + AA.uniquefloat_165 + AA.uniquefloat_166 + AA.uniquefloat_167 + AA.uniquefloat_168)/3600/2/8 as UniqueFloat_003  
                , (AA.uniquefloat_025 + AA.uniquefloat_026 + AA.uniquefloat_027 + AA.uniquefloat_028 + AA.uniquefloat_029 + AA.uniquefloat_030 + AA.uniquefloat_031 + AA.uniquefloat_032
                + AA.uniquefloat_049 + AA.uniquefloat_050 + AA.uniquefloat_051 + AA.uniquefloat_052 + AA.uniquefloat_053 + AA.uniquefloat_054 + AA.uniquefloat_055 + AA.uniquefloat_056  
                + AA.uniquefloat_073 + AA.uniquefloat_074 + AA.uniquefloat_075 + AA.uniquefloat_076 + AA.uniquefloat_077 + AA.uniquefloat_078 + AA.uniquefloat_079 + AA.uniquefloat_080 
                + AA.uniquefloat_097 + AA.uniquefloat_098 + AA.uniquefloat_099 + AA.uniquefloat_100 + AA.uniquefloat_101 + AA.uniquefloat_102 + AA.uniquefloat_103 + AA.uniquefloat_104 
                + AA.uniquefloat_121 + AA.uniquefloat_122 + AA.uniquefloat_123 + AA.uniquefloat_124 + AA.uniquefloat_125 + AA.uniquefloat_126 + AA.uniquefloat_127 + AA.uniquefloat_128)/3600/5/8 as UniqueFloat_004  
                , (AA.uniquefloat_033 + AA.uniquefloat_034 + AA.uniquefloat_035 + AA.uniquefloat_036 + AA.uniquefloat_037 + AA.uniquefloat_038 + AA.uniquefloat_039 + AA.uniquefloat_040 
                + AA.uniquefloat_057 + AA.uniquefloat_058 + AA.uniquefloat_059 + AA.uniquefloat_060 + AA.uniquefloat_061 + AA.uniquefloat_062 + AA.uniquefloat_063 + AA.uniquefloat_064 
                + AA.uniquefloat_081 + AA.uniquefloat_082 + AA.uniquefloat_083 + AA.uniquefloat_084 + AA.uniquefloat_085 + AA.uniquefloat_086 + AA.uniquefloat_087 + AA.uniquefloat_088 
                + AA.uniquefloat_105 + AA.uniquefloat_106 + AA.uniquefloat_107 + AA.uniquefloat_108 + AA.uniquefloat_109 + AA.uniquefloat_110 + AA.uniquefloat_111 + AA.uniquefloat_112 
                + AA.uniquefloat_129 + AA.uniquefloat_130 + AA.uniquefloat_131 + AA.uniquefloat_132 + AA.uniquefloat_133 + AA.uniquefloat_134 + AA.uniquefloat_135 + AA.uniquefloat_136)/3600/5/8 as UniqueFloat_005
                , (AA.uniquefloat_041 + AA.uniquefloat_042 + AA.uniquefloat_043 + AA.uniquefloat_044 + AA.uniquefloat_045 + AA.uniquefloat_046 + AA.uniquefloat_047 + AA.uniquefloat_048 
                + AA.uniquefloat_065 + AA.uniquefloat_066 + AA.uniquefloat_067 + AA.uniquefloat_068 + AA.uniquefloat_069 + AA.uniquefloat_070 + AA.uniquefloat_071 + AA.uniquefloat_072 
                + AA.uniquefloat_089 + AA.uniquefloat_090 + AA.uniquefloat_091 + AA.uniquefloat_092 + AA.uniquefloat_093 + AA.uniquefloat_094 + AA.uniquefloat_095 + AA.uniquefloat_096 
                + AA.uniquefloat_113 + AA.uniquefloat_114 + AA.uniquefloat_115 + AA.uniquefloat_116 + AA.uniquefloat_117 + AA.uniquefloat_118 + AA.uniquefloat_119 + AA.uniquefloat_120 
                + AA.uniquefloat_137 + AA.uniquefloat_138 + AA.uniquefloat_139 + AA.uniquefloat_140 + AA.uniquefloat_141 + AA.uniquefloat_142 + AA.uniquefloat_143 + AA.uniquefloat_144)/3600/5/8 as UniqueFloat_006
                , NULL AS UniqueFloat_007
                , NULL AS UniqueFloat_008
                , NULL AS UniqueFloat_009
                , NULL AS UniqueFloat_010
                , NULL AS UniqueFloat_011
                , NULL AS UniqueFloat_012
                , NULL AS UniqueFloat_013
                , NULL AS UniqueFloat_014
                , NULL AS UniqueFloat_015
                , NULL AS UniqueFloat_016
                , NULL AS UniqueFloat_017
                , NULL AS UniqueFloat_018
                , NULL AS UniqueFloat_019
                , NULL AS UniqueFloat_020
                , NULL AS UniqueFloat_021
                , NULL AS UniqueFloat_022
                , NULL AS UniqueFloat_023
                , NULL AS UniqueFloat_024
                , NULL AS UniqueFloat_025
                , NULL AS UniqueFloat_026
                , NULL AS UniqueFloat_027
                , NULL AS UniqueFloat_028
                , NULL AS UniqueFloat_029
                , NULL AS UniqueFloat_030
                , NULL AS UniqueFloat_031
                , NULL AS UniqueFloat_032
                , NULL AS UniqueFloat_033
                , NULL AS UniqueFloat_034
                , NULL AS UniqueFloat_035
                , NULL AS UniqueFloat_036
                , NULL AS UniqueFloat_037
                , NULL AS UniqueFloat_038
                , NULL AS UniqueFloat_039
                , NULL AS UniqueFloat_040
                , NULL AS UniqueFloat_041
                , NULL AS UniqueFloat_042
                , NULL AS UniqueFloat_043
                , NULL AS UniqueFloat_044
                , NULL AS UniqueFloat_045
                , NULL AS UniqueFloat_046
                , NULL AS UniqueFloat_047
                , NULL AS UniqueFloat_048
                , NULL AS UniqueFloat_049
                , NULL AS UniqueFloat_050
                , NULL AS UniqueFloat_051
                , NULL AS UniqueFloat_052
                , NULL AS UniqueFloat_053
                , NULL AS UniqueFloat_054
                , NULL AS UniqueFloat_055
                , NULL AS UniqueFloat_056
                , NULL AS UniqueFloat_057
                , NULL AS UniqueFloat_058
                , NULL AS UniqueFloat_059
                , NULL AS UniqueFloat_060
                , NULL AS UniqueFloat_061
                , NULL AS UniqueFloat_062
                , NULL AS UniqueFloat_063
                , NULL AS UniqueFloat_064
                , NULL AS UniqueFloat_065
                , NULL AS UniqueFloat_066
                , NULL AS UniqueFloat_067
                , NULL AS UniqueFloat_068
                , NULL AS UniqueFloat_069
                , NULL AS UniqueFloat_070
                , NULL AS UniqueFloat_071
                , NULL AS UniqueFloat_072
                , NULL AS UniqueFloat_073
                , NULL AS UniqueFloat_074
                , NULL AS UniqueFloat_075
                , NULL AS UniqueFloat_076
                , NULL AS UniqueFloat_077
                , NULL AS UniqueFloat_078
                , NULL AS UniqueFloat_079
                , NULL AS UniqueFloat_080
                , NULL AS UniqueFloat_081
                , NULL AS UniqueFloat_082
                , NULL AS UniqueFloat_083
                , NULL AS UniqueFloat_084
                , NULL AS UniqueFloat_085
                , NULL AS UniqueFloat_086
                , NULL AS UniqueFloat_087
                , NULL AS UniqueFloat_088
                , NULL AS UniqueFloat_089
                , NULL AS UniqueFloat_090
                , NULL AS UniqueFloat_091
                , NULL AS UniqueFloat_092
                , NULL AS UniqueFloat_093
                , NULL AS UniqueFloat_094
                , NULL AS UniqueFloat_095
                , NULL AS UniqueFloat_096
                , NULL AS UniqueFloat_097
                , NULL AS UniqueFloat_098
                , NULL AS UniqueFloat_099
                , NULL AS UniqueFloat_100
                , NULL AS UniqueFloat_101
                , NULL AS UniqueFloat_102
                , NULL AS UniqueFloat_103
                , NULL AS UniqueFloat_104
                , NULL AS UniqueFloat_105
                , NULL AS UniqueFloat_106
                , NULL AS UniqueFloat_107
                , NULL AS UniqueFloat_108
                , NULL AS UniqueFloat_109
                , NULL AS UniqueFloat_110
                , NULL AS UniqueFloat_111
                , NULL AS UniqueFloat_112
                , NULL AS UniqueFloat_113
                , NULL AS UniqueFloat_114
                , NULL AS UniqueFloat_115
                , NULL AS UniqueFloat_116
                , NULL AS UniqueFloat_117
                , NULL AS UniqueFloat_118
                , NULL AS UniqueFloat_119
                , NULL AS UniqueFloat_120
                , NULL AS UniqueFloat_121
                , NULL AS UniqueFloat_122
                , NULL AS UniqueFloat_123
                , NULL AS UniqueFloat_124
                , NULL AS UniqueFloat_125
                , NULL AS UniqueFloat_126
                , NULL AS UniqueFloat_127
                , NULL AS UniqueFloat_128
                , NULL AS UniqueFloat_129
                , NULL AS UniqueFloat_130
                , NULL AS UniqueFloat_131
                , NULL AS UniqueFloat_132
                , NULL AS UniqueFloat_133
                , NULL AS UniqueFloat_134
                , NULL AS UniqueFloat_135
                , NULL AS UniqueFloat_136
                , NULL AS UniqueFloat_137
                , NULL AS UniqueFloat_138
                , NULL AS UniqueFloat_139
                , NULL AS UniqueFloat_140
                , NULL AS UniqueFloat_141
                , NULL AS UniqueFloat_142
                , NULL AS UniqueFloat_143
                , NULL AS UniqueFloat_144
                , NULL AS UniqueFloat_145
                , NULL AS UniqueFloat_146
                , NULL AS UniqueFloat_147
                , NULL AS UniqueFloat_148
                , NULL AS UniqueFloat_149
                , NULL AS UniqueFloat_150
                , NULL AS UniqueFloat_151
                , NULL AS UniqueFloat_152
                , NULL AS UniqueFloat_153
                , NULL AS UniqueFloat_154
                , NULL AS UniqueFloat_155
                , NULL AS UniqueFloat_156
                , NULL AS UniqueFloat_157
                , NULL AS UniqueFloat_158
                , NULL AS UniqueFloat_159
                , NULL AS UniqueFloat_160
                , NULL AS UniqueFloat_161
                , NULL AS UniqueFloat_162
                , NULL AS UniqueFloat_163
                , NULL AS UniqueFloat_164
                , NULL AS UniqueFloat_165
                , NULL AS UniqueFloat_166
                , NULL AS UniqueFloat_167
                , NULL AS UniqueFloat_168
                , NULL AS UniqueFloat_169
                , NULL AS UniqueFloat_170
                , NULL AS UniqueFloat_171
                , NULL AS UniqueFloat_172
                , NULL AS UniqueFloat_173
                , NULL AS UniqueFloat_174
                , NULL AS UniqueFloat_175
                , NULL AS UniqueFloat_176
                , NULL AS UniqueFloat_177
                , NULL AS UniqueFloat_178
                , NULL AS UniqueFloat_179
                , NULL AS UniqueFloat_180
                , NULL AS UniqueFloat_181
                , NULL AS UniqueFloat_182
                , NULL AS UniqueFloat_183
                , NULL AS UniqueFloat_184
                , NULL AS UniqueFloat_185
                , NULL AS UniqueFloat_186
                , NULL AS UniqueFloat_187
                , NULL AS UniqueFloat_188
                , NULL AS UniqueFloat_189
                , NULL AS UniqueFloat_190
                , NULL AS UniqueFloat_191
                , NULL AS UniqueFloat_192
                , NULL AS UniqueFloat_193
                , NULL AS UniqueFloat_194
                , NULL AS UniqueFloat_195
                , NULL AS UniqueFloat_196
                , NULL AS UniqueFloat_197
                , NULL AS UniqueFloat_198
                , NULL AS UniqueFloat_199
                , NULL AS UniqueFloat_200
                , NULL AS UniqueJson_001 
            FROM gtwpd.model_usedata AA 
            WHERE 1 = 1
                AND AA.product = 'maple' 
                AND AA.project = 'LoginTag' 
                AND AA.version = 'R0_1_2'
                AND AA.dt = '[:DateNoLine]'
                AND AA.step = 'RawData'; 
        """
        return "MakePreProcessOrderSQLInsert", [orderSQL1]


